### ISSUE TITLE
Put the sponsors on the Github repo

### ISSUE THREAD

**Issue by Yeikzy** [Discord-Resources-Wiki/Discord-Resources-Wiki#193]
I propose to integrate Discord Wiki Resources into the sponsors program of Github, so that the repo can also activate the sponsors button to support the project.

**Comment by rydixulous** [comment]
this is currently being discussed within our team.
My question is: would you see yourself / other users sponsor our project? yes / no and why ?

**Comment by Yeikzy** [comment]
> this is currently being discussed within our team. My question is: would you see yourself / other users sponsor our project? yes / no and why ?

I think the project could attract some sponsors interested in the documentation and information of the discord wiki, financial support could make the Discord Resources project grow.

**Comment by rydixulous** [comment]
> > this is currently being discussed within our team. My question is: would you see yourself / other users sponsor our project? yes / no and why ?
> 
> I think the project could attract some sponsors interested in the documentation and information of the discord wiki, financial support could make the Discord Resources project grow.

As we already made the project open source, the content of it isn't, in my opinion, the reason to sponsor us, but just to show support and let us spend more time building it.
I am not that familiar with GitHub sponsorship, but I do hope we give people enough value in order for them to support us as well.

If someone notices this issue, feel free to mention your opinion here! the more the merrier.
We will also discuss this internally in order to understand how we want to approach this, as V2 is being worked on (as well as some other feature improvements).

**Comment by Yeikzy** [comment]
Okay 👌🏼

**Comment by Yeikzy** [comment]
@rydixulous Following this pull request I propose to activate the sponsors directly on the Github organization.
https://github.com/Discord-Resources-Wiki/Discord-Resources-Wiki/pull/309

**Comment by rjt-rockx** [comment]
Quick update on this:
Due to some issues with GitHub sponsors requiring a Stripe Connect account, we were unable to activate GitHub sponsors directly on the organization. 
However, we can still enable a sponsor button to be displayed on the repository iirc, hence the linked PR above. 
We'll look into enabling GitHub sponsors again once we can set it up.
